
<div class="container">

    <p>A Bootstrap/jQuery plugin to preview image uploads.</p>

    <form action="/jqueryimageupload/index/upload" method="post" enctype="multipart/form-data" name="jqueryFormUpload">
        <!-- bootstrap-imageupload. -->
        <div class="imageupload panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left">Upload Image</h3>
                <div class="btn-group pull-right">
                    <button type="button" class="btn btn-default active">File</button>
                    <button type="button" class="btn btn-default">URL</button>
                </div>
            </div>
            <div class="file-tab panel-body">
                <label class="btn btn-default btn-file">
                    <span>Browse</span>
                    <!-- The file is stored here. -->
                    <input type="file" name="image-file">
                </label>
                <button type="button" class="btn btn-default">Remove</button>
                <!-- Submit button -->
                <button type="submit" class="btn btn-default">Submit</button>

            </div>
            <div class="url-tab panel-body">
                <div class="input-group">
                    <input type="text" class="form-control hasclear" placeholder="Image URL">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default">Submit</button>
                    </div>
                </div>
                <button type="button" class="btn btn-default">Remove</button>
                <!-- The URL is stored here. -->
                <input type="hidden" name="image-file">
                <!-- Submit button -->
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    </form>


    <!-- bootstrap-imageupload method buttons. -->
    <button type="button" id="imageupload-disable" class="btn btn-danger">Disable</button>
    <button type="button" id="imageupload-enable" class="btn btn-success">Enable</button>
    <button type="button" id="imageupload-reset" class="btn btn-primary">Reset</button>


    <script>
        require([
            'jquery',
            'bootstrap',
            'bootstrap_imageupload'
        ], function($, bootstrap, bootstrap_imageupload){
            'use strict'
            $(function() {


                var $imageupload = $('.imageupload');
                $imageupload.imageupload();


                $('#imageupload-disable').on('click', function() {
                    $imageupload.imageupload('disable');
                    $(this).blur();
                })

                $('#imageupload-enable').on('click', function() {
                    $imageupload.imageupload('enable');
                    $(this).blur();
                })

                $('#imageupload-reset').on('click', function() {
                    $imageupload.imageupload('reset');
                    $(this).blur();
                });

            });
        });
    </script>

</div>
