<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Tax\Block\Item\Price\Renderer */
$customHelper = $this->helper('Luckyduck\Customization\Helper\Miscellaneous');
?>
<?php $_item = $block->getItem() ?>
    <?php if ($block->displayPriceInclTax() || $block->displayBothPrices()) : ?>
        <span class="price-wrapper price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
            
            <span class="price"><?php echo $customHelper->getSymbol().' '.$customHelper->getcurrencyWithoutsymbol($_item->getPriceInclTax());?></span>

        </span>
    <?php endif; ?>
    <?php if ($block->displayPriceExclTax() || $block->displayBothPrices()) : ?>
        <span class="price-wrapper price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
            
            <span class="price"><?php echo $customHelper->getSymbol().' '.$customHelper->getcurrencyWithoutsymbol($_item->getCalculationPrice());?></span>

        </span>
    <?php endif; ?>
