<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */


$product = $block->getProduct();

$currentStock = $this->helper('\Luckyduck\Customization\Helper\Miscellaneous')->getproductStock($product);

$packageType = $product->getAttributeText('capacity_in_cl');
$availableqty = $this->helper('Luckyduck\Customization\Helper\Data')->getAvailableOrderQty($currentStock,$packageType);


$wihshlistHelper = $this->helper('\Magento\Wishlist\Helper\Data');
$datapost =  $wihshlistHelper->getAddParams($block->getProduct(),array('qty' => reset($availableqty)));
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @noEscape */ $datapost ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
