<?php
//echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('custom_header')->toHtml();
?>
<div class="header-container">
	<div class="block15"> &nbsp;</div>
	<div class="block45">
		<div class="blockleft">
			<div class="blockSearch">
				<div class="input-box">
			        <label for="search">Suche:</label>
			        <input id="search" type="search" name="q" value="" class="input-text required-entry" maxlength="128" placeholder="Gesamten Shop durchsuchen …" autocomplete="off">
			        <button type="submit" title="Suche" class="button search-button"><span><span>Suche</span></span></button>
			    </div>
			</div>
			<div class="customLink">
				<a href="#">Erweiterte Suche</a>
			</div>
			<div class="navigation">
				<div class="nav-main">
					<ul>
						<li><a href="#">Weine kaufen</a></li>
						<li><a href="#">Weine verkaufen</a></li>
						<li><a href="#">Weinwissen</a></li>
						<li><a href="#">Downloads</a></li>
						<li><a href="#">Service</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="block40">
		<div class="blockright">
			<div class="haederLinks">
				<div class="options-currency">
					<select>
						<option>GBP</option><option>EUR</option><option>HKD</option><option>JPY</option><option>CHF</option><option>USD</option>
					</select>
				</div>
				<div class="options-language">
					<a href="#">DE</a>|<a href="#">EN</a>
				</div>
			</div>---1
			<div class="navigation">
				<div class="nav-options">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">Konditionen</a></li>
						<li><a href="#">Kontakt</a></li>
						<li><a href="#">Über uns</a></li>
						<li><a href="#">Newsletter</a></li>
					</ul>
				</div>
			</div>----2
			<div class="header-options">
				<ul>
					<li class="wishlist">
						<span class="icon"></span>
						<span class="label">Merkliste</span>
					</li>
					<li class="account">
						<span class="icon"></span>
						<span class="label">Konto</span>
					</li>
					<li class="cart">
						<span class="icon"></span>
						<span class="label">Warenkorb</span>
					</li>
				</ul>
			</div>---3
		</div>--------
	</div>
</div>