<?php
	$_helper = $this->helper('Luckyduck\Customization\Helper\Data');
	$url  = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);

?>
<div class="nav-main">
	<ul>
		<?php if($_helper->isLoggedIn()) { ?>
			<li><a href="<?php echo $this->getUrl("customer/account/");?>"><?= $block->escapeHtml(__('My Account')) ?></a></li>
			<li><a href="<?php echo $this->getUrl("wishlist/");?>"><?= $block->escapeHtml(__('My Wishlist')) ?></a></li>
			<li><a href="<?php echo $this->getUrl("checkout/cart/");?>"><?= $block->escapeHtml(__('My Cart')) ?></a></li>
			<li><a href="<?php echo $this->getUrl("checkout/");?>"><?= $block->escapeHtml(__('Checkout')) ?></a></li>
			<li><a href="<?php echo $this->getUrl("customer/account/logout");?>"><?= $block->escapeHtml(__('Log Out')) ?></a></li>
		<?php } else { ?>
			<li><a href="<?php echo $this->getUrl("wishlist/");?>"><?= $block->escapeHtml(__('My Wishlist')) ?></a></li>
			<li><a href="<?php echo $this->getUrl("customer/account/create");?>"><?= $block->escapeHtml(__('Register')) ?></a></li>
			<li><a href="<?php echo $this->getUrl('customer/account/login', array('referer' => base64_encode($url)));?>"><?= $block->escapeHtml(__('Log In')) ?></a></li>
		<?php } ?>
	</ul>
</div>

