<?php
namespace Boxes\Commandline\Console;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputOption;

/*
 * insert to command line : bin/magento boxes:command --Name="Noom test"
 */
class CommandList extends Command{

    /**
     * @var string
     */
    protected string $name = 'Name';

    /**
     * @return void
     */
    protected function configure()
    {
        $commandOption = [new InputOption($this->name, null , InputOption::VALUE_REQUIRED,'Name')];
        $this->setName('boxes:command');
        $this->setDescription('Demo for test Command line');
        $this->setDefinition( $commandOption );

        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|void
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if($name = $input->getOption($this->name)){

            $output->writeln('Hello '.$name);
        }else{

            $output->writeln('Hello world !!! Symfony command line');
        }

        //parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
