<?php
/**
* @var \Boxes\DbActions\Block\Display $block
*/

?>

<h2>Welcome to Test <?=  $block->sayHello(); ?>.</h2>


<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php
    foreach ($block->getPostCollection() as $key=>$post){
        echo '<tr>
                    <td>'.$post->getPostId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getPostContent().'</td>
                  </tr>';
    }
    ?>
</table>

