<div class="maincontent">
    <div class="title">
        <span class="widget-title"><?php echo __("Shop Widget Title : "); ?></span>
        <span class="widget-title-val"><?php echo $block->getData('shop_title'); ?></span>
    </div>
    <div class="description">
        <span class="widget-desc"><?php echo __("Shop Widget Description : "); ?></span>
        <span class="widget-desc-val"><?php echo $block->getData('shop_description'); ?></span>
    </div>
</div>
