<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\Widget\HideMoreOptions $block */
$dataAmJsAttribute = "data-am-js=%s";

if ($block->getIsState()) {
    $buttonSelector = sprintf($dataAmJsAttribute, 'show-more_button_state');
    $itemSelector = '[' . sprintf($dataAmJsAttribute, 'shopby-container') . ']';
    $numberUnfoldedOptions = $block->getUnfoldedOptions();
    $isModeDropdown = false;
} else {
    $filterSetting = $block->getFilterSetting();
    $isModeDropdown = $filterSetting->getDisplayMode()
        == \Amasty\Shopby\Model\Source\DisplayMode::MODE_DROPDOWN;
    $filterCode = $block->escapeHtml($filterSetting->getFilterCode());
    $buttonSelector = sprintf($dataAmJsAttribute, 'am-filter-items-'.  $filterCode. '-show-more');
    $itemSelector = '.am-filter-items-' . $filterCode;
    $numberUnfoldedOptions = $filterSetting->getNumberUnfoldedOptions();
}
?>

<?php if (!$isModeDropdown): ?>
    <a class="am-show-more"
            title="<?= $block->escapeHtml(__("More"))?>" <?= $block->escapeHtml($buttonSelector) ?>
            data-text-more="<?= $block->escapeHtml(__("More"))?>"
            data-text-less="<?= $block->escapeHtml(__("Show less"))?>"
            data-is-hide="false">
        <?= $block->escapeHtml(__("Show less"))?>
    </a>

    <script type="text/x-magento-init">
        {
            "<?= /* @noEscape */ $itemSelector ?>": {
                "amShopbyFilterHideMoreOptions": {
                    "numberUnfoldedOptions": <?= $block->escapeHtml($numberUnfoldedOptions) ?>,
                    "selectors": {
                        "button": "[<?= /* @noEscape */ $buttonSelector ?>]"
                    },
                    "isState": "<?= /* @noEscape */ $block->getIsState() ?>"
                }
            }
        }
    </script>
<?php endif; ?>
