<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <div class="fieldset">
        <div class="field email required">
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" placeholder="<?= $block->escapeHtml(__('Email')) ?>">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action remind" href="<?= $block->escapeUrl($this->getUrl('customer/account/login', ['_current' => true, '_use_rewrite' => true])) ?>"><span><?= $block->escapeHtml(__('Back to Login')) ?></span></a>
        </div>
    </div>
</form>
