<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
$helper = $this->helper('Luckyduck\Customization\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cust = $objectManager->get('Magento\Customer\Model\SessionFactory');
$custddata = $cust->create();
if($custddata->getCustomer()->getId()){
	$firstName = $custddata->getCustomer()->getFirstname();
	$lastName = $custddata->getCustomer()->getLastname();
}else{
	$firstName = "";
	$lastName = "";
}
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    
    <div class="cell-1 fields">   
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="<?= $firstName ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="<?= $lastName ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </div> 
    <div class="cell-2 fields">
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>

</form>

<div class="store-info">
    <div><?php echo $helper->getConfig('general/store_information/name'); ?></div>
    <div><?php echo $helper->getConfig('general/store_information/street_line1'); ?></div>
    <div><?php echo __('Telephone') . " " . $helper->getConfig('general/store_information/phone') . " | " . "Fax +41(0)41 240 70 82" . " | " . "E-Mail: " . $helper->getConfig('trans_email/ident_general/email'); ?></div>
    <div><?php echo __('Office opening hours:'); ?></div>
    <div><?php echo $helper->getConfig('general/store_information/hours'); ?></div>
    <div><?php echo __('For collections/deliveries these hours also apply but please telephone us beforehand.'); ?></div>
</div>