<!--div id="vue-test" data-mage-init='{ "Macademy_JsFun/js/vue-test":{ "message": "Another test" } }'>
    <h1>{{ message }}</h1>
</div-->


<div id="vue-test" data-mage-init='{ "Macademy_JsFun/js/vue-test":{ "message": "Another test" } }'>
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "Macademy_JsFun/js/vue-test": {
                "message": "Declarative test Code"
            }
        }
    }
</script>
